var codeMap = {
    "0": "Transaction Successful",
    "1": "Invalid Beneficiary Mobile No / MAS",
    "2": "Amount limit exceeded for the customer",
    "3": "Frozen Account",
    "4": "NRE Account",
    "5": "Closed Account",
    "6": "NET Debit cap exceeded for member bank",
    "7": "Transaction not permitted for this account type",
    "8": "Transaction limit exceeded for this account type",
    "9": "Transaction not allowed as this is non-reloadable card",
    "10": "No routing for institution/network",
    "11": "Time out at NPCI",
    "12": "Bank not live on IMPS account / IFSC based fund transfer",
    "13": "Invalid amount",
    "14": "Duplicate transaction in IMPS",
    "15": "Beneficiary is Merchant",
    "16": "Format Error",
    "17": "Transaction not found",
    "18": "NPCI/Issuing bank is not connected or down",
    "19": "Unconfigured RC",
    "20": "Invalid Response Code",
    "21": "Decline on verification",
    "24": "Transaction not allowed - Amount greater than 2 lakh",
    "30": "No transaction response from NPCI",
    "31": "No transaction response from CDCI",
    "32": "Time out at ICICI CBS for outward transaction (Beneficiary non-ICICI customer)",
    "33": "Time out at ICICI CBS for intra transaction (Beneficiary ICICI customer)",
    "34": "Suspect Fraud",
    "35": "Invalid Message",
    "36": "Invalid Transaction",
    "37": "Invalid Amount",
    "38": "Transfer amount exceeds limit Transaction not processed as client txn date expired",
    "51": "Transaction declined by beneficiary bank due to insufficient funds",
    "52": "Invalid Account",
    "60": "Reason Unknown (Technical decline by IMPS)",
    "61": "Reason Unknown (Technical decline by CBS)",
    "62": "Reason Unknown (Technical decline by NPCI)",
    "63": "No response from IMPS switch",
    "65": "Exceed Amount limit",
    "70": "OCH - Technical Failure",
    "71": "OCH – Invalid Amount",
    "72": "OCH Invalid account number",
    "73": "OCH Timeout – BC to check final status of transaction after RECON",
    "74": "OCH Batch limit has been exhausted service",
    "75": "Duplicate transaction in OCH",
    "76": "OCH defined limit decreased and transaction decline",
    "77": "Balance Inquiry has been decline due to technical error",
    "80": "Initial request is already been processed",
    "96": "Unable to process",
    "101": "IMPS Switch Not reachable",
    "102": "Connectivity disconnected, transaction in processing mode.",
    "201": "Invalid Beneficiary IFSC Code or NBIN",
    "202": "Customer Limit Exceeded",
    "203": "Foreign inward remittance not allowed",
    "204": "Transaction not allowed as invalid payment reference",
    "205": "Transaction amount less then Rs.1",
    "206": "Transaction not allowed as invalid remitter account",
    "207": "Transaction not allowed as general error",
    "208": "Foreign inward remittance for P2P only",
    "403": "Unauthorized API Access",
    "901": "Invalid BC",
    "902": "Authentication failed",
    "903": "Invalid BC Retailer",
    "904": "No response from DCMS",
    "905": "Card Validation failed",
    "915": "BC Nodal Account not supported",
    "916": "BC Nodal Account not Found",
    "917": "BC Retailer code mapping not Found",
    "918": "BC daily amount high",
    "919": "BC monthly amount high",
    "920": "BC min invalid amount",
    "921": "BC max invalid amount",
    "922": "Channel GST amount missing",
    "923": "Channel service charge amount missing",
    "924": "Channel retailer state missing"
};